/* /go/ hub — tabs + GA4 click events. Generated by _deploy/build-linkinbio.py.
   External on purpose: script-src on several portfolio CSPs has no
   'unsafe-inline', and 'self' is allowed everywhere. */
(function () {
  'use strict';
  var ds = (document.currentScript && document.currentScript.dataset) || {};

  /* GA4 bootstrap — same house pattern as js/ga4.js on the sites that have
     one (host-gated, measurement only). Only runs where the page carries a
     data-ga4 id, i.e. sites with no analytics file of their own. */
  if (ds.ga4 && ds.host &&
      new RegExp('(^|\\.)' + ds.host.replace(/\./g, '\\.') + '$', 'i')
        .test(location.hostname) && !window.gtag) {
    window.dataLayer = window.dataLayer || [];
    window.gtag = function () { window.dataLayer.push(arguments); };
    window.gtag('js', new Date());
    window.gtag('config', ds.ga4, {
      anonymize_ip: true,
      allow_google_signals: false,
      allow_ad_personalization_signals: false
    });
    var lib = document.createElement('script');
    lib.async = true;
    lib.src = 'https://www.googletagmanager.com/gtag/js?id=' + ds.ga4;
    document.head.appendChild(lib);
  }

  function track(name, params) {
    if (typeof window.gtag !== 'function') return;
    params.transport_type = 'beacon';
    window.gtag('event', name, params);
  }

  document.body.className = 'js';
  var tabs = [].slice.call(document.querySelectorAll('[role="tab"]'));
  if (!tabs.length) return;
  var secondId = tabs[1] ? tabs[1].getAttribute('aria-controls') : null;

  function show(id, push) {
    tabs.forEach(function (t) {
      var pid = t.getAttribute('aria-controls'), on = pid === id;
      t.setAttribute('aria-selected', on ? 'true' : 'false');
      t.tabIndex = on ? 0 : -1;
      document.getElementById(pid).hidden = !on;
    });
    if (push && history.replaceState) {
      history.replaceState(null, '',
        id === secondId ? '#' + id : location.pathname + location.search);
      track('tab_view', { tab: id });
    }
  }

  tabs.forEach(function (t, i) {
    t.addEventListener('click', function () {
      show(t.getAttribute('aria-controls'), true);
    });
    t.addEventListener('keydown', function (e) {
      if (e.key !== 'ArrowRight' && e.key !== 'ArrowLeft') return;
      var n = tabs[(i + (e.key === 'ArrowRight' ? 1 : tabs.length - 1)) % tabs.length];
      n.focus(); n.click();
    });
  });

  function sync() {
    show(secondId && location.hash === '#' + secondId ? secondId : tabs[0].getAttribute('aria-controls'), false);
  }
  window.addEventListener('hashchange', sync);
  sync();

  document.addEventListener('click', function (e) {
    var el = e.target;
    while (el && el !== document && !(el.tagName === 'A' && el.hasAttribute('data-t'))) {
      el = el.parentNode;
    }
    if (el && el !== document) {
      track('bio_click', { link_label: el.getAttribute('data-t'), link_url: el.href });
    }
  });
})();
