/* /go/ hub — tabs, source attribution, GA4 + first-party events.
   Generated by _deploy/build-linkinbio.py. External on purpose: script-src on
   several portfolio CSPs has no 'unsafe-inline', and 'self' is allowed everywhere. */
(function () {
  'use strict';
  var ds = (document.currentScript && document.currentScript.dataset) || {};

  /* GA4 bootstrap — same house pattern as js/ga4.js on the sites that have
     one (host-gated, measurement only). Only runs where the page carries a
     data-ga4 id, i.e. sites with no analytics file of their own. */
  if (ds.ga4 && ds.domain &&
      new RegExp('(^|\\.)' + ds.domain.replace(/\./g, '\\.') + '$', 'i')
        .test(location.hostname) && !window.gtag) {
    window.dataLayer = window.dataLayer || [];
    window.gtag = function () { window.dataLayer.push(arguments); };
    window.gtag('js', new Date());
    window.gtag('config', ds.ga4, {
      anonymize_ip: true,
      allow_google_signals: false,
      allow_ad_personalization_signals: false
    });
    var lib = document.createElement('script');
    lib.async = true;
    lib.src = 'https://www.googletagmanager.com/gtag/js?id=' + ds.ga4;
    document.head.appendChild(lib);
  }

  /* Source attribution. The hub URL is the same in every bio, so a tap from
     the Facebook Page, a YouTube channel link or a QR scan used to leave with
     utm_source=instagram (the build-time default, data-src). Precedence:
       1. ?s=<code> on the hub URL — fb, yt, x, li, wa, tt, th, qr, em, sms
          (put https://<domain>/go/?s=fb in the Facebook Page's website field)
       2. utm_source on the hub URL (the QR carries utm_source=qr)
       3. the referrer host (Instagram's in-app browser sends l.instagram.com)
       4. the default — nothing is rewritten
     Only same-property links (they carry utm_campaign=go) are touched; the
     third-party profile links in the social row stay clean. */
  var SHORT = { ig: 'instagram', fb: 'facebook', yt: 'youtube', x: 'x', li: 'linkedin',
                wa: 'whatsapp', tt: 'tiktok', th: 'threads', qr: 'qr', em: 'email', sms: 'sms' };
  var HOSTS = [['instagram.com', 'instagram'], ['facebook.com', 'facebook'], ['t.co', 'x'],
               ['x.com', 'x'], ['twitter.com', 'x'], ['youtube.com', 'youtube'], ['youtu.be', 'youtube'],
               ['linkedin.com', 'linkedin'], ['lnkd.in', 'linkedin'], ['threads.net', 'threads'],
               ['threads.com', 'threads'], ['tiktok.com', 'tiktok'], ['whatsapp.com', 'whatsapp'],
               ['wa.me', 'whatsapp'], ['pinterest.com', 'pinterest'], ['reddit.com', 'reddit'],
               ['t.me', 'telegram'], ['bing.com', 'bing'], ['duckduckgo.com', 'duckduckgo']];
  var SOCIAL = { instagram: 1, facebook: 1, x: 1, youtube: 1, linkedin: 1, threads: 1, tiktok: 1,
                 whatsapp: 1, pinterest: 1, reddit: 1, telegram: 1 };
  function hostIs(h, k) { return h === k || h.slice(-k.length - 1) === '.' + k; }
  function source() {
    var q, s = '', h = '';
    try { q = new URLSearchParams(location.search); } catch (e) { return null; }
    s = (q.get('s') || '').toLowerCase();
    if (s) return SHORT[s] || s.replace(/[^a-z0-9_-]/g, '').slice(0, 24) || null;
    s = (q.get('utm_source') || '').toLowerCase().replace(/[^a-z0-9_.-]/g, '').slice(0, 24);
    if (s) return s;
    try { h = new URL(document.referrer).hostname.toLowerCase(); } catch (e) { return null; }
    if (!h || (ds.domain && hostIs(h, ds.domain))) return null;
    for (var i = 0; i < HOSTS.length; i++) { if (hostIs(h, HOSTS[i][0])) return HOSTS[i][1]; }
    if (/(^|\.)google\./.test(h)) return 'google';
    return h.replace(/^www\./, '').slice(0, 24);
  }
  var src = source();
  if (src && src !== ds.src) {
    var medium = src === 'qr' ? 'offline' : (src === 'email' || src === 'sms') ? src
               : SOCIAL[src] ? 'bio' : 'referral';
    [].forEach.call(document.querySelectorAll('a[href*="utm_campaign=go"]'), function (a) {
      try {
        var u = new URL(a.href);
        u.searchParams.set('utm_source', src);
        u.searchParams.set('utm_medium', medium);
        a.href = u.toString();
      } catch (e) { /* leave the build-time UTM */ }
    });
  }

  function track(name, params) {
    if (typeof window.gtag !== 'function') return;
    params.transport_type = 'beacon';
    window.gtag('event', name, params);
  }

  /* First-party telemetry — the in-house Linktree analytics. One POST per
     view / click / share to api-php (data-api), JSON as text/plain so there is
     no CORS preflight; sendBeacon survives the page unloading on a tap. */
  function beacon(kind, extra) {
    if (!ds.api || !ds.prop) return;
    var payload = JSON.stringify({
      property: ds.prop, kind: kind, label: extra.label || null,
      url: extra.url || null, path: location.pathname, ref: document.referrer || null,
      src: src || ds.src || null
    });
    try {
      if (navigator.sendBeacon &&
          navigator.sendBeacon(ds.api, new Blob([payload], { type: 'text/plain' }))) return;
      fetch(ds.api, { method: 'POST', body: payload, keepalive: true, mode: 'cors',
                      credentials: 'omit', headers: { 'Content-Type': 'text/plain' } })
        .catch(function () {});
    } catch (err) { /* telemetry must never break the hub */ }
  }
  beacon('view', {});

  document.body.className = 'js';

  var shareBtn = document.querySelector('[data-share]');
  if (shareBtn) {
    shareBtn.addEventListener('click', function () {
      var url = shareBtn.getAttribute('data-url');
      track('bio_share', { link_url: url });
      beacon('share', { url: url });
      if (navigator.share) {
        navigator.share({ title: document.title, text: shareBtn.getAttribute('data-text') || '',
                          url: url }).catch(function () {});
        return;
      }
      var reveal = function () {   // no share sheet, no clipboard: show the URL under the QR
        var q = document.getElementById('qr'), b = document.querySelector('.qrbtn');
        if (q) { q.hidden = false; if (b) b.setAttribute('aria-expanded', 'true'); }
      };
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(url).then(function () {
          var was = shareBtn.textContent;
          shareBtn.textContent = shareBtn.getAttribute('data-done');
          setTimeout(function () { shareBtn.textContent = was; }, 1800);
        }, reveal);
      } else { reveal(); }
    });
  }
  var qrBtn = document.querySelector('.qrbtn'), qr = document.getElementById('qr');
  if (qrBtn && qr) {
    qrBtn.addEventListener('click', function () {
      var open = qr.hidden;
      qr.hidden = !open;
      qrBtn.setAttribute('aria-expanded', open ? 'true' : 'false');
      if (open) { track('bio_qr_open', {}); }
    });
  }
  var tabs = [].slice.call(document.querySelectorAll('[role="tab"]'));
  if (!tabs.length) return;
  var secondId = tabs[1] ? tabs[1].getAttribute('aria-controls') : null;

  function show(id, push) {
    tabs.forEach(function (t) {
      var pid = t.getAttribute('aria-controls'), on = pid === id;
      t.setAttribute('aria-selected', on ? 'true' : 'false');
      t.tabIndex = on ? 0 : -1;
      document.getElementById(pid).hidden = !on;
    });
    if (push && history.replaceState) {
      history.replaceState(null, '',
        id === secondId ? '#' + id : location.pathname + location.search);
      track('tab_view', { tab: id });
    }
  }

  tabs.forEach(function (t, i) {
    t.addEventListener('click', function () {
      show(t.getAttribute('aria-controls'), true);
    });
    t.addEventListener('keydown', function (e) {
      if (e.key !== 'ArrowRight' && e.key !== 'ArrowLeft') return;
      var n = tabs[(i + (e.key === 'ArrowRight' ? 1 : tabs.length - 1)) % tabs.length];
      n.focus(); n.click();
    });
  });

  function sync() {
    show(secondId && location.hash === '#' + secondId ? secondId : tabs[0].getAttribute('aria-controls'), false);
  }
  window.addEventListener('hashchange', sync);
  sync();

  document.addEventListener('click', function (e) {
    var el = e.target;
    while (el && el !== document && !(el.tagName === 'A' && el.hasAttribute('data-t'))) {
      el = el.parentNode;
    }
    if (el && el !== document) {
      track('bio_click', { link_label: el.getAttribute('data-t'), link_url: el.href });
      beacon('click', { label: el.getAttribute('data-t'), url: el.href });
    }
  });
})();
